[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*" # Aplica este encabezado a todas las páginas de tu sitio
  [headers.values]
    Permissions-Policy = "camera=*"